const productsData = [
  {
    id: '1',
    title: 'Omaru Polka Birthday Celebration 2022',
    price: '2,200,000 VND',
    image: '../images/polka_BD2022_top_400x.png',
    tags: ['Holo', 'Live', 'Memorials'],
    desc: 'This product is to celebrate the birthday of Omaru Polka from hololive.<br><br>◇Birthday Merch Complete Set...',
    images: [
      './images/polka_BD2022_top_900x.webp',
      './images/polka_BD2022_set_900x.webp',
      './images/polka_BD2022_tanpin01_900x.webp',
      './images/polka_BD2022_tanpin02_900x.webp',
      './images/polka_BD2022_tanpin03_900x.webp',
    ],
    options: [
      {
        name: 'All set and bonus',
        price: '2200000 VND',
        imageIndex: 1,
        stock: 'In Stock',
      },
      {
        name: 'Rubber Mat',
        price: '599000 VND',
        imageIndex: 2,
        stock: 'In Stock',
      },
      {
        name: 'Backpack',
        price: '1395000 VND',
        imageIndex: 3,
        stock: 'In Stock',
      },
      {
        name: 'Headband',
        price: '499000 VND',
        imageIndex: 4,
        stock: 'In Stock',
      },
    ],
  },
  {
    id: '2',
    title: 'Nekomata Okayu Birthday Celebration 2022',
    price: '1,500,000 VND',
    image: '../images/nekomataokayu_birthday2022_top_0215_800x.png',
    tags: ['Holo', 'Live', 'Memorials'],
    desc: 'This product is to celebrate the birthday of Nekomata Okayu...',
    images: [
      './images/nekomataokayu_birthday2022_top_0215_800x.webp',
      './images/nekomataokayu_birthday2022_full_0218_800x.webp',
    ],
    options: [
      {
        name: 'All set',
        price: '1500000 VND',
        imageIndex: 1,
        stock: 'In Stock',
      },
    ],
  },
  {
    id: '3',
    title: 'Minato Aqua AQUA IRO SUPER DREAM Ver.',
    price: '5,460,000 VND',
    image: '../images/Minato_Aqua_AQUA_IRO_SUPER_DREAM.jpg',
    tags: ['Holo', 'Live', 'Figures'],
    desc: 'From the popular VTuber group Hololive Production...',
    images: ['../images/MinatoAquaAQUAIROSUPERDREAMVer.01.jpg'],
    options: [
      {
        name: 'Figure',
        price: '5460000 VND',
        imageIndex: 0,
        stock: 'In Stock',
      },
    ],
  },
  {
    id: '4',
    title: '"Beyond the stage" Live Goods Resale',
    price: '170,000 VND',
    image: '../images/0224BeyondtheStage__1_900x.png',
    tags: ['Holo', 'Live', 'Memorials'],
    desc: 'Resale of the live merch...',
    images: ['./images/0224BeyondtheStage__full1_800x.webp'],
    options: [
      {
        name: 'T-shirt',
        price: '850000 VND',
        imageIndex: 0,
        stock: 'In Stock',
      },
    ],
  },
  {
    id: '5',
    title: 'IRyS Half-Year Celebration',
    price: '390,000 VND',
    image: '../images/irys-half-year.png',
    tags: ['Hololive', 'English', 'CDs'],
    desc: 'Half-year celebration of IRyS...',
    images: ['./images/IRYS_HalfYearTOP.webp'],
    options: [
      {
        name: 'Key Chain',
        price: '390000 VND',
        imageIndex: 0,
        stock: 'Out of Stock',
      },
    ],
  },
  {
    id: '6',
    title: 'Houshou Marine 1/7 Scale Figure',
    price: '9,200,000 VND',
    image: '../images/Marine_17_scale_figure.jpg',
    tags: ['Holo', 'Live', 'Figures'],
    desc: 'Captain of the Houshou Pirates...',
    images: ['./images/HoushouMarineFigure1.webp'],
    options: [
      {
        name: 'Figure',
        price: '9200000 VND',
        imageIndex: 0,
        stock: 'In Stock',
      },
    ],
  },
  {
    id: '7',
    title: 'Towa 1st EP "Scream"',
    price: '440,000 VND',
    image: '../images/Towa_scream_EP.png',
    tags: ['Holo', 'Live', 'CDs'],
    desc: '1st EP of Tokoyami Towa...',
    images: ['./images/TowaEPScream1.webp'],
    options: [
      { name: 'CD', price: '440000 VND', imageIndex: 0, stock: 'In Stock' },
    ],
  },
  {
    id: '8',
    title: '[First Press Limited Edition] Minato Aqua 1st EP',
    price: '440,000 VND',
    image: '../images/0128_aqua_top_400x.png',
    tags: ['Holo', 'Live', 'CDs'],
    desc: 'Minato Aqua’s 1st EP...',
    images: ['./images/Minato_aqua_1stEP_top_900x.webp'],
    options: [
      { name: 'CD', price: '440000 VND', imageIndex: 0, stock: 'In Stock' },
    ],
  },
  {
    id: '9',
    title: 'Moona Hoshinova Birthday Celebration 2022',
    price: '399,000 VND',
    image: '../images/moona_BD2022_top_en_png_800x.webp',
    tags: ['Hololive', 'Indonesia', 'Memorials'],
    desc: 'Birthday of Moona Hoshinova...',
    images: ['./images/moona_BD2022_top_en_png_1000x.webp'],
    options: [
      {
        name: 'Full Set',
        price: '2500000 VND',
        imageIndex: 0,
        stock: 'Out of Stock',
      },
    ],
  },
  {
    id: '10',
    title: 'Hoshimachi Suisei 1st Album "Still Still Stellar"',
    price: '649,000 VND',
    image: '../images/SSStellar-Sales.jpg',
    tags: ['Holo', 'Live', 'CDs'],
    desc: 'First full album...',
    images: ['./images/1220__1st_StillStillStellar_1.webp'],
    options: [
      {
        name: 'Album',
        price: '649000 VND',
        imageIndex: 0,
        stock: 'Out of Stock',
      },
    ],
  },
]
